### ISSUE TITLE
Transform files into textual format before committing here

### ISSUE THREAD

**Issue by rjmunro** [staldates/words-of-worship-files#2]
Could use something like XML, JSON, YAML or maybe something textual and simple (like start choruses with `::chorus::`, bridges with  `::bridge::` and highlighted lines with `*` or something). To be really useful, we'd need scripts to convert to and from WoW format in a lossless way.

**Comment by jamesremuscat** [comment]
I get what you're saying, but I'm not seeing the benefit:
- We can already convert WoW files to text to let git diff them usefully - see https://github.com/jamesremuscat/wowlint/tree/develop (though admittedly that won't get shown on Github);
- I can point StA people here to download an archive of the songs we use, ready-to-go, rather than having to send them to the church computer;
- It would be much more complicated to require conversion on checkin and checkout; as-is, it's as straightforward as anything involving git can be to keep files up to date;
- I don't really think we should be republishing copyrighted material in an easy-to-search-and-DMCA form ;-)
