### ISSUE TITLE
Possible copyright infringement

### ISSUE THREAD

**Issue by NathanJPhillips** [staldates/words-of-worship-files#3]
While I have a communication from CCLI confirming that one licence holder can share covered content with another licence holder, making the songs publicly available here might be viewed more as publishing them rather than sharing them, which I doubt would be covered. Would the church be safer from possible financial liability if this was a private repository?

**Comment by jamesremuscat** [comment]
Hi Nathan,

Thanks for the comment, and I appreciate the concern. That's part of the reason that the files here are in WoW format rather than converting them to another, more easily readable format (as someone did actually request that I do in #2).

As you surmise, the purpose of this repository is to facilitate sharing WoW resources across systems covered by St Aldates's CCLI licence; it's not intended for any other purpose, and certainly not for wider distribution of copyrighted material. I'll also state here (more for the public record than for you!) that the @staldates organisation and @st-aldates-sound-desk user on Github are 'unofficial' and set up by members of the production team at church, without any special anointing from church leadership. ;-)

This also means that there is no budget to create a private Github repository, though I would consider hosting it privately elsewhere if concerns were raised (though this may well reduce its utility for other StA users).

Should any rightsholders or representative organisations have a concern with this repository I will be more than happy to take the necessary steps to ensure that those concerns are addressed and resolved.
